//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Project/Settings/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Auto-generated input actions wrapper class.
/// Provides type-safe access to all defined input actions.
/// </summary>
public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""b7c8e5f7-8c3d-4a1e-9f5b-2c4d6e8a0b1c"",
            ""actions"": [
                {""name"": ""Move"", ""type"": ""Value"", ""id"": ""a1b2c3d4-e5f6-7890-abcd-ef1234567890"", ""expectedControlType"": ""Vector2""},
                {""name"": ""Jump"", ""type"": ""Button"", ""id"": ""b2c3d4e5-f6a7-8901-bcde-f12345678901""},
                {""name"": ""Dash"", ""type"": ""Button"", ""id"": ""c3d4e5f6-a7b8-9012-cdef-123456789012""},
                {""name"": ""Attack"", ""type"": ""Button"", ""id"": ""d4e5f6a7-b8c9-0123-defa-234567890123""},
                {""name"": ""Parry"", ""type"": ""Button"", ""id"": ""e5f6a7b8-c9d0-1234-efab-345678901234""},
                {""name"": ""Skill"", ""type"": ""Button"", ""id"": ""f6a7b8c9-d0e1-2345-fabc-456789012345""},
                {""name"": ""Interact"", ""type"": ""Button"", ""id"": ""a7b8c9d0-e1f2-3456-abcd-567890123456""}
            ],
            ""bindings"": [
                {""name"": ""WASD"", ""id"": ""1"", ""path"": ""2DVector"", ""action"": ""Move"", ""isComposite"": true},
                {""name"": ""up"", ""id"": ""2"", ""path"": ""<Keyboard>/w"", ""action"": ""Move"", ""isPartOfComposite"": true},
                {""name"": ""down"", ""id"": ""3"", ""path"": ""<Keyboard>/s"", ""action"": ""Move"", ""isPartOfComposite"": true},
                {""name"": ""left"", ""id"": ""4"", ""path"": ""<Keyboard>/a"", ""action"": ""Move"", ""isPartOfComposite"": true},
                {""name"": ""right"", ""id"": ""5"", ""path"": ""<Keyboard>/d"", ""action"": ""Move"", ""isPartOfComposite"": true},
                {""name"": """", ""id"": ""6"", ""path"": ""<Gamepad>/leftStick"", ""action"": ""Move""},
                {""name"": """", ""id"": ""7"", ""path"": ""<Keyboard>/space"", ""action"": ""Jump""},
                {""name"": """", ""id"": ""8"", ""path"": ""<Gamepad>/buttonSouth"", ""action"": ""Jump""},
                {""name"": """", ""id"": ""9"", ""path"": ""<Keyboard>/leftShift"", ""action"": ""Dash""},
                {""name"": """", ""id"": ""10"", ""path"": ""<Gamepad>/rightTrigger"", ""action"": ""Dash""},
                {""name"": """", ""id"": ""11"", ""path"": ""<Mouse>/leftButton"", ""action"": ""Attack""},
                {""name"": """", ""id"": ""12"", ""path"": ""<Keyboard>/j"", ""action"": ""Attack""},
                {""name"": """", ""id"": ""13"", ""path"": ""<Gamepad>/buttonWest"", ""action"": ""Attack""},
                {""name"": """", ""id"": ""14"", ""path"": ""<Mouse>/rightButton"", ""action"": ""Parry""},
                {""name"": """", ""id"": ""15"", ""path"": ""<Keyboard>/k"", ""action"": ""Parry""},
                {""name"": """", ""id"": ""16"", ""path"": ""<Gamepad>/leftShoulder"", ""action"": ""Parry""},
                {""name"": """", ""id"": ""17"", ""path"": ""<Keyboard>/l"", ""action"": ""Skill""},
                {""name"": """", ""id"": ""18"", ""path"": ""<Gamepad>/buttonNorth"", ""action"": ""Skill""},
                {""name"": """", ""id"": ""19"", ""path"": ""<Keyboard>/e"", ""action"": ""Interact""},
                {""name"": """", ""id"": ""20"", ""path"": ""<Gamepad>/buttonEast"", ""action"": ""Interact""}
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""c8d9e0f1-2345-6789-0abc-def012345678"",
            ""actions"": [
                {""name"": ""Pause"", ""type"": ""Button"", ""id"": ""d9e0f123-4567-890a-bcde-f01234567890""}
            ],
            ""bindings"": [
                {""name"": """", ""id"": ""21"", ""path"": ""<Keyboard>/escape"", ""action"": ""Pause""},
                {""name"": """", ""id"": ""22"", ""path"": ""<Gamepad>/start"", ""action"": ""Pause""}
            ]
        }
    ],
    ""controlSchemes"": [
        {""name"": ""Keyboard&Mouse"", ""bindingGroup"": ""Keyboard&Mouse"", ""devices"": [{""devicePath"": ""<Keyboard>""}]},
        {""name"": ""Gamepad"", ""bindingGroup"": ""Gamepad"", ""devices"": [{""devicePath"": ""<Gamepad>""}]}
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
        m_Gameplay_Jump = m_Gameplay.FindAction("Jump", throwIfNotFound: true);
        m_Gameplay_Dash = m_Gameplay.FindAction("Dash", throwIfNotFound: true);
        m_Gameplay_Attack = m_Gameplay.FindAction("Attack", throwIfNotFound: true);
        m_Gameplay_Parry = m_Gameplay.FindAction("Parry", throwIfNotFound: true);
        m_Gameplay_Skill = m_Gameplay.FindAction("Skill", throwIfNotFound: true);
        m_Gameplay_Interact = m_Gameplay.FindAction("Interact", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Pause = m_UI.FindAction("Pause", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, PlayerInputActions.Gameplay.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, PlayerInputActions.UI.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private readonly InputAction m_Gameplay_Move;
    private readonly InputAction m_Gameplay_Jump;
    private readonly InputAction m_Gameplay_Dash;
    private readonly InputAction m_Gameplay_Attack;
    private readonly InputAction m_Gameplay_Parry;
    private readonly InputAction m_Gameplay_Skill;
    private readonly InputAction m_Gameplay_Interact;

    public struct GameplayActions
    {
        private @PlayerInputActions m_Wrapper;
        public GameplayActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Gameplay_Move;
        public InputAction @Jump => m_Wrapper.m_Gameplay_Jump;
        public InputAction @Dash => m_Wrapper.m_Gameplay_Dash;
        public InputAction @Attack => m_Wrapper.m_Gameplay_Attack;
        public InputAction @Parry => m_Wrapper.m_Gameplay_Parry;
        public InputAction @Skill => m_Wrapper.m_Gameplay_Skill;
        public InputAction @Interact => m_Wrapper.m_Gameplay_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private readonly InputAction m_UI_Pause;

    public struct UIActions
    {
        private @PlayerInputActions m_Wrapper;
        public UIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_UI_Pause;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
    }
    public UIActions @UI => new UIActions(this);
}
